// <auto-generated />
namespace AUTOCAR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Inicial4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicial4));
        
        string IMigrationMetadata.Id
        {
            get { return "202011252106232_Inicial4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
